const projects = [
  {
    title: "KERF ENT Hospital",
    link: "https://kerfenthospital.com/",
    year: "2024",
    subtitle: "Official website for Experts in advanced ENT care",
    workType: "w/ Codeface",
    imp: false,
  },
  {
    title: "Aix Capital",
    link: "https://aixcapital.co.uk/",
    year: "2024",
    subtitle: "75 Years of Driving Growth and Innovation with Integrity",
    workType: "w/ Codeface",
    imp: true,
  },
  {
    title: "Projx Solutions",
    link: "https://www.projxsolutions.in/",
    year: "2024",
    subtitle: "Logistics & Supply Chain Solutions",
    workType: "f/ Jn Graphics",
    imp: false,
  },
  {
    title: "Crosssphere",
    link: "https://crosssphere-web.vercel.app/",
    year: "2024",
    subtitle: "Spices. Export. Worldwide.",
    workType: "f/ BranXcel",
    imp: false,
  },
  {
    title: "Khanway",
    link: "https://khanway-frontend.vercel.app/",
    year: "2024",
    subtitle: "Official Website for World's First Goodwill NFW",
    workType: "w/ Codeface",
    imp: false,
  },
  {
    title: "Nutryfit",
    link: "https://www.nutryfit.in/",
    year: "2024",
    subtitle: "Personalized nutrition for your goals.",
    workType: "w/ Websters",
    imp: false,
  },
  {
    title: "DRMS",
    link: "https://www.drmsgroup.com/",
    year: "2024",
    subtitle: "Official Website for Cardiac Care",
    workType: "w/ Speakerbox Media",
    imp: true,
  },
  {
    title: "BOD",
    link: "https://www.boddesignhub.com/",
    year: "2024",
    subtitle: "Official Website for Architecture design",
    workType: "w/ Speakerbox Media",
    imp: true,
  },
  {
    title: "Trendzo",
    link: "https://trendzo-jn-graphics-git-main-mdodoing.vercel.app/",
    year: "2023",
    subtitle: "Official Website for Fashion Shop",
    workType: "f/ Jn Graphics",
    imp: false,
  },
  {
    title: "Montzo Life",
    link: "https://www.montzo.com/",
    year: "2023",
    subtitle: "Official Website for Dressing Brand",
    workType: "w/ Speakerbox Media",
    imp: true,
  },
  {
    title: "Farsa Group",
    link: "https://www.farsagroup.com/",
    year: "2023",
    subtitle: "Official Website for Farsa Group",
    workType: "w/ Speakerbox Media",
    imp: true,
  },
  {
    title: "Taasco Engineering",
    link: "https://www.taasco.co/",
    year: "2023",
    subtitle: "Official Website for Engineering",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "Hasa Group",
    link: "https://hasa-website.vercel.app/",
    year: "2023",
    subtitle: "Premium Steel Doors and Windows for Your Home",
    workType: "f/ BrandXcel",
    imp: false,
  },
  {
    title: "Earthlane",
    link: "https://earthlane.in/",
    year: "2023",
    subtitle: "Official Website for infrastructure development",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "Multisystems logistics",
    link: "https://www.multisystem.me/",
    year: "2023",
    subtitle: "Official Website for warehousing and distribution",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "Easydine",
    link: "https://www.easydine.net/",
    year: "2023",
    subtitle:
      "Official Website for A Personalized and Modern Approach to Dining",
    workType: "w/ Speakerbox Media",
    imp: true,
  },
  {
    title: "Pixzl",
    link: "https://pixzl.vercel.app/",
    year: "2023",
    subtitle: "Next Generation Architectural Visualization",
    workType: "w/ Speakerbox Media",
    imp: true,
  },
  {
    title: "Grafixy",
    link: "https://grafixy.netlify.app/",
    year: "2023",
    subtitle: "Official Website for Grafixy Agency",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "Zahi Fashion",
    link: "https://zahi-fashion-website.vercel.app/",
    year: "2023",
    subtitle: "Official Website for Zahi Fashion",
    workType: "w/ Jn Graphics",
    imp: false,
  },
  {
    title: "AYS Jewels",
    link: "https://aysjewels.in/",
    year: "2023",
    subtitle: "Official Website for Jewels",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "YuRaCo Constructions",
    link: "https://yurco-co.vercel.app/",
    year: "2023",
    subtitle: "Official Website for Constructions",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "Cargotrack",
    link: "https://cargotrack-website.vercel.app/",
    year: "2023",
    subtitle: "Official Website for Relocation",
    workType: "w/ Speakerbox Media",
    imp: false,
  },
  {
    title: "Crosssphere Store",
    link: "https://store-crosssphere-git-main-mdodoing.vercel.app/",
    year: "2023",
    subtitle: "Export the species all over the world.",
    workType: "F/ BrandXcel",
    imp: false,
  },
].sort((a, b) => (b.imp ? 1 : 0) - (a.imp ? 1 : 0));

export default projects;
